# Generated by Django 4.2.11 on 2025-07-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('factory_year', models.IntegerField(blank=True, null=True)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.FloatField(blank=True, max_length=7, null=True)),
                ('doors', models.IntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
